name: Test
on:
  push:
  workflow_dispatch:
jobs:
  echo_text:
    name: echo_text
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: checkout
      uses: actions/checkout@master
    - name: Run a single-line script
      run: |
        cd /home/runner/work/jpg2webp/jpg2webp
        python test1.py
